name: Publish Package on Merge To Master

on:
  push:
    branches: 
      - master

jobs:
  publish-npm:
    name: Publish Patch Version To NPM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
          scope: '@theosyslack'
      - run: git config --global user.name "${{ secrets.GIT_CONFIG_NAME }}"
      - run: git config --global user.email "${{ secrets.GIT_CONFIG_EMAIL }}"
      - run: yarn
      - run: yarn publish --patch
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
